// Copyright (c) Narvalo.Org. All rights reserved. See LICENSE.txt in the project root for license information.

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool. Changes to this file may cause incorrect
// behavior and will be lost if the code is regenerated.
//
// Runtime Version: 4.0.30319.42000
// Microsoft.VisualStudio.TextTemplating: 15.0
// </auto-generated>
//------------------------------------------------------------------------------

namespace Narvalo.Applicative
{
    using System;
    using System.Collections.Generic;

    using FsCheck.Xunit;
    using Xunit;

    public static partial class FallibleFacts
    {
        #region Repeat()

        [Fact]
        public static void Repeat_ThrowsArgumentOutOfRangeException_ForNegativeCount()
        {
            var source = Fallible.Of(1);

            Assert.Throws<ArgumentOutOfRangeException>(() => Fallible.Repeat(source, -1));
        }

        #endregion

        #region Zip()

        [Fact]
        public static void Zip2_ThrowsArgumentNullException_ForNullZipper()
        {
            var first = Fallible.Of(1);
            var second = Fallible.Of(2);
            Func<int, int, int> zipper = null;

            Assert.Throws<ArgumentNullException>(() => first.Zip(second, zipper));
            Assert.Throws<ArgumentNullException>(() => FallibleExtensions.Zip(first, second, zipper));
        }

        [Fact]
        public static void Zip3_ThrowsArgumentNullException_ForNullZipper()
        {
            var first = Fallible.Of(1);
            var second = Fallible.Of(2);
            var third = Fallible.Of(3);
            Func<int, int, int, int> zipper = null;

            Assert.Throws<ArgumentNullException>(() => first.Zip(second, third, zipper));
            Assert.Throws<ArgumentNullException>(() => FallibleExtensions.Zip(first, second, third, zipper));
        }

        [Fact]
        public static void Zip4_ThrowsArgumentNullException_ForNullZipper()
        {
            var first = Fallible.Of(1);
            var second = Fallible.Of(2);
            var third = Fallible.Of(3);
            var fourth = Fallible.Of(4);
            Func<int, int, int, int, int> zipper = null;

            Assert.Throws<ArgumentNullException>(() => first.Zip(second, third, fourth, zipper));
            Assert.Throws<ArgumentNullException>(() => FallibleExtensions.Zip(first, second, third, fourth, zipper));
        }

        [Fact]
        public static void Zip5_ThrowsArgumentNullException_ForNullZipper()
        {
            var first = Fallible.Of(1);
            var second = Fallible.Of(2);
            var third = Fallible.Of(3);
            var fourth = Fallible.Of(4);
            var fifth = Fallible.Of(4);
            Func<int, int, int, int, int, int> zipper = null;

            Assert.Throws<ArgumentNullException>(() => first.Zip(second, third, fourth, fifth, zipper));
            Assert.Throws<ArgumentNullException>(() => FallibleExtensions.Zip(first, second, third, fourth, fifth, zipper));
        }

        #endregion

        #region Select()

        [Fact]
        public static void Select_ThrowsArgumentNullException_ForNullSelector()
        {
            var source = Fallible.Of(1);
            Func<int, int> selector = null;

            Assert.Throws<ArgumentNullException>(() => source.Select(selector));
            Assert.Throws<ArgumentNullException>(() => FallibleExtensions.Select(source, selector));
        }

        #endregion

        #region SelectMany()

        [Fact]
        public static void SelectMany_ThrowsArgumentNullException_ForNullValueSelector()
        {
            var source = Fallible.Of(1);
            Func<int, Fallible<int>> valueSelector = null;
            Func<int, int, int> resultSelector = (i, j) => i + j;

            Assert.Throws<ArgumentNullException>(() => source.SelectMany(valueSelector, resultSelector));
            Assert.Throws<ArgumentNullException>(() => FallibleExtensions.SelectMany(source, valueSelector, resultSelector));
        }

        [Fact]
        public static void SelectMany_ThrowsArgumentNullException_ForNullResultSelector()
        {
            var source = Fallible.Of(1);
            var middle = Fallible.Of(2);
            Func<int, Fallible<int>> valueSelector = _ => middle;
            Func<int, int, int> resultSelector = null;

            Assert.Throws<ArgumentNullException>(() => source.SelectMany(valueSelector, resultSelector));
            Assert.Throws<ArgumentNullException>(() => FallibleExtensions.SelectMany(source, valueSelector, resultSelector));
        }

        #endregion

        #region Functor Rules

        [Fact(DisplayName = "Fallible<T> - The identity map is a fixed point for Select.")]
        public static void Satisfies_FirstFunctorLaw()
        {
            // Arrange
            var me = Fallible.Of(1);

            // Act
            var left = me.Select(Stubs<int>.Identity);
            var right = Stubs<Fallible<int>>.Identity(me);

            // Assert
            Assert.True(left.Equals(right));
        }

        [Fact(DisplayName = "Fallible<T> - Select preserves the composition operator.")]
        public static void Satisfies_FunctorSecondRule()
        {
            // Arrange
            var me = Fallible.Of(1);
            Func<int, long> g = val => (long)2 * val;
            Func<long, long> f = val => 3 * val;

            // Act
            var left = me.Select(_ => f(g(_)));
            var right = me.Select(g).Select(f);

            // Assert
            Assert.True(left.Equals(right));
        }

        #endregion

        #region Monad Rules

        [Property(DisplayName = "Fallible<T> - Of is a left identity for Bind (first monad rule).")]
        public static bool Of_IsLeftIdentityForBind(int arg0, float arg1)
        {
            Func<int, Fallible<float>> binder = val => Fallible.Of(arg1 * val);

            var left = Fallible.Of(arg0).Bind(binder);
            var right = binder(arg0);

            return left.Equals(right);
        }

        [Property(DisplayName = "Fallible<T> - Of is a left identity for Compose (first monad rule).")]
        public static bool Of_IsLeftIdentityForCompose(int arg0, float arg1)
        {
            Func<int, Fallible<int>> of = val => Fallible.Of(val);
            Func<int, Fallible<float>> fun = val => Fallible.Of(arg1 * val);

            var left = of.Compose(fun).Invoke(arg0);
            var right = fun(arg0);

            return left.Equals(right);
        }

        [Property(DisplayName = "Fallible<T> - Of is a right identity for Bind (second monad rule).")]
        public static bool Of_IsRightIdentityForBind(int arg0)
        {
            var me = Fallible.Of(arg0);

            var left = me.Bind(Fallible.Of);
            var right = me;

            return left.Equals(right);
        }

        [Property(DisplayName = "Fallible<T> - Of is a right identity for Compose (second monad rule).")]
        public static bool Of_IsRightIdentityForCompose(int arg0, float arg1)
        {
            Func<float, Fallible<float>> of = val => Fallible.Of(val);
            Func<int, Fallible<float>> fun = val => Fallible.Of(arg1 * val);

            var left = fun.Compose(of).Invoke(arg0);
            var right = fun(arg0);

            return left.Equals(right);
        }

        [Property(DisplayName = "Fallible<T> - Bind is associative (third monad law).")]
        public static bool Bind_IsAssociative(short arg0, int arg1, long arg2)
        {
            var me = Fallible.Of(arg0);

            Func<short, Fallible<int>> f = val => Fallible.Of(arg1);
            Func<int, Fallible<long>> g = val => Fallible.Of(arg2);

            var left = me.Bind(f).Bind(g);
            var right = me.Bind(val => f(val).Bind(g));

            return left.Equals(right);
        }

        #endregion
    }
}

